spring.application.name=OneFeed Server
onefeed.plugins.directory-path=./server/plugins
onefeed.plugins.plugin-config-path=./server/plugin-config.yaml
logging.level.root=INFO
springdoc.default-produces-media-type=application/json
spring.jackson.default-property-inclusion=non_absent
