spring.application.name=OneFeed Server
onefeed.plugins.directory-path=./onefeed-server/plugins
onefeed.plugins.plugin-config-path=./onefeed-server/plugin-config.yaml
logging.level.root=INFO
springdoc.default-produces-media-type=application/json
spring.jackson.default-property-inclusion=non_null
