<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <artifactId>onefeed-server-cacher-plugin-sdk</artifactId>

  <name>OneFeed Server Cacher Plugin SDK</name>
  <description>SDK for OneFeed Server Cacher plugins</description>
  <url>https://github.com/justinquinnb/OneFeed-Server</url>

  <parent>
    <groupId>dev.jqb.onefeedserver</groupId>
    <artifactId>onefeed-server</artifactId>
    <version>${revision}</version>
    <relativePath>../../../pom.xml</relativePath>
  </parent>

  <dependencies>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
    </dependency>
    <dependency>
      <groupId>org.pf4j</groupId>
      <artifactId>pf4j</artifactId>
    </dependency>
    <dependency>
      <groupId>dev.jqb.onefeedserver</groupId>
      <artifactId>onefeed-server-plugin-sdk</artifactId>
      <version>${revision}</version>
    </dependency>
    <dependency>
      <groupId>dev.jqb.onefeed</groupId>
      <artifactId>onefeed-core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
    </dependency>
    <dependency>
      <groupId>io.projectreactor</groupId>
      <artifactId>reactor-test</artifactId>
    </dependency>
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
    </dependency>
  </dependencies>
</project>