<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>dev.jqb.onefeedserver</groupId>
    <artifactId>onefeed-server</artifactId>
    <version>${revision}</version>
  </parent>

  <artifactId>onefeed-server-bom</artifactId>
  <name>OneFeed Server BOM</name>
  <packaging>pom</packaging>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>dev.jqb.onefeedserver</groupId>
        <artifactId>onefeed-server-app</artifactId>
        <version>${revision}</version>
      </dependency>
      <dependency>
        <groupId>dev.jqb.onefeedserver</groupId>
        <artifactId>onefeed-server-rss-compat-plugin</artifactId>
        <version>${revision}</version>
      </dependency>
      <dependency>
        <groupId>dev.jqb.onefeedserver</groupId>
        <artifactId>onefeed-server-plugin-sdk</artifactId>
        <version>${revision}</version>
      </dependency>
      <dependency>
        <groupId>dev.jqb.onefeedserver</groupId>
        <artifactId>onefeed-server-cacher-plugin-sdk</artifactId>
        <version>${revision}</version>
      </dependency>
      <dependency>
        <groupId>dev.jqb.onefeedserver</groupId>
        <artifactId>onefeed-server-provider-plugin-sdk</artifactId>
        <version>${revision}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>